import pygame
from pygame.locals import *
import sys


class Othello:
    SCREEN_SIZE: tuple = (640, 480)

    BOARD_COLOUR: tuple = (0, 128, 0)

    @classmethod
    def main (cls) -> None:
        pygame.init ()
        screen: pygame.Surface = pygame.display.set_mode (cls.SCREEN_SIZE)

        while True:
            screen.fill ((0, 0, 0))

            # pygame.draw.rect (screen, BOARD_COLOUR, )

            pygame.display.update ()
            pygame.time.wait (33)

            for event in pygame.event.get ():
                if event.type == QUIT:
                    pygame.quit ()
                    sys.exit ()


if __name__ == '__main__':
    Othello.main ()

